E-biblioteka/Models/Author.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.InteropServices;
using System.Web;

namespace E_biblioteka.Models
{
    public class Author
    {
        [Display(Name = "Author Id")]
        [Key]
        public long AuthorId { get; set; }
        [Required]
        [StringLength(64, ErrorMessage = "Author's name must not exceed 64 characters!")]
        public string Name { get; set; }
        [Display(Name = "Image")]
        public string ImageUrl { get; set; }
        public string Description { get; set; }
        public virtual List<Book> Books { get; set; }

        public Author()
        {
            Books = new List<Book>();
        }
    }
}

E-biblioteka/Controllers/AuthorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using E_biblioteka.Models;
using PagedList;

namespace E_biblioteka.Controllers
{
    public class AuthorsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Authors
        public ActionResult Index(int? page, string orderBy, string search)
        {
            var pageNumber = page ?? 1;
            var pageSize = 9;
            var authors = from a in db.Authors
                          select a;
            IOrderedQueryable<Author> model;

            if (!string.IsNullOrEmpty(search))
            {
                authors = authors.Where(iterator => iterator.Name.Contains(search));
            }

            switch (orderBy)
            {
                case "name-ascending":
                    model = authors.OrderBy(a => a.Name);
                    break;
                case "name-descending":
                    model = authors.OrderByDescending(a => a.Name);
                    break;
                default:
                    model = authors.OrderBy(a => a.Name);
                    break;
            }
            if (page == null)
                ViewBag.Page = pageNumber;
            else
                ViewBag.Page = page;
            ViewBag.OrderBy = orderBy;
            ViewBag.Search = search;
            return View(model.ToPagedList(pageNumber, pageSize));
        }

        // GET: Authors/Details/5
        public ActionResult Details(long? id, int page, string orderBy, string search)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.Page = page;
            ViewBag.OrderBy = orderBy;
            ViewBag.Search = search;
            Author author = db.Authors.Include(a => a.Books).FirstOrDefault(a => a.AuthorId == id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // GET: Authors/Create
        [Authorize(Roles = "Administrator")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Authors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult Create([Bind(Include = "AuthorId,Name,ImageUrl,Description")] Author author)
        {
            if (ModelState.IsValid)
            {
                db.Authors.Add(author);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(author);
        }

        // GET: Authors/Edit/5
        [Authorize(Roles = "Administrator, Employee")]
        public ActionResult Edit(long? id, int page, string orderBy, string search)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.Page = page;
            ViewBag.OrderBy = orderBy;
            ViewBag.Search = search;
            Author author = db.Authors.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // POST: Authors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, Employee")]
        public ActionResult Edit([Bind(Include = "AuthorId,Name,ImageUrl,Description")] Author author, int page, string orderBy, string search)
        {
            if (ModelState.IsValid)
            {
                db.Entry(author).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { page, orderBy, search });
            }
            return View(author);
        }

        // GET: Authors/Delete/5
        [Authorize(Roles = "Administrator")]
        public ActionResult Delete(long? id, int page, string orderBy, string search)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.Page = page;
            ViewBag.OrderBy = orderBy;
            ViewBag.Search = search;
            Author author = db.Authors.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // POST: Authors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult DeleteConfirmed(long id, int page, string orderBy, string search)
        {
            Author author = db.Authors.Find(id);
            db.Authors.Remove(author);
            db.SaveChanges();
            return RedirectToAction("Index", new { page, orderBy, search });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

E-biblioteka/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using E_biblioteka.Models;
using E_biblioteka.Models.Forum;
using PagedList;

namespace E_biblioteka.Controllers
{
    public class BooksController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Books
        public ActionResult Index(int? page, string orderBy, string search, string bookGenre)
        {
            var pageNumber = page ?? 1;
            var pageSize = 9;
            var books = db.Books.Include(b => b.Author);

            IQueryable<string> genreQuery = from b in db.Books
                                            orderby b.Genre
                                            select b.Genre;

            if (!string.IsNullOrEmpty(search))
            {
                books = books.Where(iterator => iterator.Name.Contains(search) || iterator.Author.Name.Contains(search));
            }

            if (!string.IsNullOrEmpty(bookGenre))
            {
                books = books.Where(iterator => iterator.Genre == bookGenre);
            }

            switch (orderBy)
            {
                case "title-ascending":
                    books = books.OrderBy(b => b.Name);
                    break;
                case "title-descending":
                    books = books.OrderByDescending(b => b.Name);
                    break;
                case "rating-descending":
                    books = books.OrderByDescending(b => b.Rating);
                    break;
                case "year-ascending":
                    books = books.OrderBy(b => b.Year);
                    break;
                case "year-descending":
                    books = books.OrderByDescending(b => b.Year);
                    break;
                default:
                    books = books.OrderByDescending(b => b.Rating);
                    break;
            }

            var booksVM = new BooksViewModel
            {
                Genres = genreQuery.Distinct().ToList(),
                Books = books.ToPagedList(pageNumber, pageSize)
            };
            if (page == null)
                ViewBag.Page = pageNumber;
            else
                ViewBag.Page = page;
            ViewBag.OrderBy = orderBy;
            ViewBag.Search = search;
            ViewBag.BookGenre = bookGenre;
            return View(booksVM);
        }

        // GET: Books/Details/5
        public ActionResult Details(long? id, int page, string orderBy, string search, string bookGenre)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.Page = page;
            ViewBag.OrderBy = orderBy;
            ViewBag.Search = search;
            ViewBag.BookGenre = bookGenre;
            Book book = db.Books.Include(b => b.Author).FirstOrDefault(b => b.BookId == id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // GET: Books/Create
        [Authorize(Roles = "Administrator")]
        public ActionResult Create()
        {
            var model = new AddAuthorToBook()
            {
                Book = new Book(),
                Authors = db.Authors.ToList(),
                SelectedAuthorId = -1,
                SelectedBookId = -1
            };

            return View(model);
        }

        [Authorize(Roles = "Administrator")]
        public ActionResult CreateFromRequest(Request request)
        {
            Book newBook = new Book
            {
                Name = request.Title,
            };
            var model = new AddAuthorToBook()
            {
                Book = newBook,
                Authors = db.Authors.ToList(),
                SelectedAuthorId = -1,
                SelectedBookId = -1
            };
            db.Requests.Remove(db.Requests.Find(request.RequestId));
            db.SaveChanges();
            return View(model);
        }

        // POST: Books/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult Create(AddAuthorToBook model)
        {
            if (ModelState.IsValid)
            {
                Book book = new Book()
                {
                    Name = model.Book.Name,
                    Genre = model.Book.Genre,
                    Year = model.Book.Year,
                    Rating = model.Book.Rating,
                    Description = model.Book.Description,
                    ImageUrl = model.Book.ImageUrl
                };

                Author author = db.Authors.Find(model.SelectedAuthorId);
                if (author == null)
                {
                    model = new AddAuthorToBook()
                    {
                        Book = new Book(),
                        Authors = db.Authors.ToList(),
                        SelectedAuthorId = -1,
                        SelectedBookId = -1
                    };

                    return View(model);
                }
                book.Author = author;

                db.Books.Add(book);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(model);
        }

        // GET: Books/Edit/5
        [Authorize(Roles = "Administrator, Employee")]
        public ActionResult Edit(int? id, int page, string orderBy, string search, string bookGenre)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ViewBag.Page = page;
            ViewBag.OrderBy = orderBy;
            ViewBag.Search = search;
            ViewBag.BookGenre = bookGenre;

            Book book = db.Books.Find(id);
            if (book == null)
                return HttpNotFound();

            var model = new AddAuthorToBook()
            {
                Book = new Book(),
                Authors = db.Authors.ToList(),
                SelectedAuthorId = book.Author.AuthorId,
                SelectedBookId = -1
            };

            model.Book = book;
            return View(model);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, Employee")]
        public ActionResult Edit(AddAuthorToBook model, int page, string orderBy, string search, string bookGenre)
        {
            if (ModelState.IsValid)
            {
                Book book = db.Books.Find(model.Book.BookId);
                if (book == null)
                    return HttpNotFound();

                book.Name = model.Book.Name;
                book.Description = model.Book.Description;
                book.Genre = model.Book.Genre;
                book.ImageUrl = model.Book.ImageUrl;
                book.Rating = model.Book.Rating;
                book.Year = model.Book.Year;
                book.InStock = model.Book.InStock;

                Author author = db.Authors.Find(model.SelectedAuthorId);
                if (author == null)
                {
                    model = new AddAuthorToBook()
                    {
                        Book = new Book(),
                        Authors = db.Authors.ToList(),
                        SelectedAuthorId = -1,
                        SelectedBookId = -1
                    };
                    return View(model);
                }
                book.Author = author;

                db.SaveChanges();
                return RedirectToAction("Index", new { page, orderBy, search, bookGenre });
            }
            return View(model);
        }

        // GET: Books/Delete/5
        [Authorize(Roles = "Administrator")]
        public ActionResult Delete(long? id, int page, string orderBy, string search, string bookGenre)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ViewBag.Page = page;
            ViewBag.OrderBy = orderBy;
            ViewBag.Search = search;
            ViewBag.BookGenre = bookGenre;

            Book book = db.Books.Include(b => b.Author).FirstOrDefault(b => b.BookId == id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult DeleteConfirmed(long id, int page, string orderBy, string search, string bookGenre)
        {
            Book book = db.Books.Include(b => b.Author).FirstOrDefault(b => b.BookId == id);
            db.Books.Remove(book);
            db.SaveChanges();
            return RedirectToAction("Index", new { page, orderBy, search, bookGenre });
        }

        [Authorize(Roles = "Member, Moderator")]
        public ActionResult UpVote(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Include(b => b.Author).FirstOrDefault(b => b.BookId == id);
            if (book == null)
            {
                return HttpNotFound();
            }
            if (book.Rating < 5)
            {

E-biblioteka/Views/Authors/Create.cshtml
@model E_biblioteka.Models.Author

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Author</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImageUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImageUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

E-biblioteka/Views/Authors/Delete.cshtml
@model E_biblioteka.Models.Author

@{
    ViewBag.Title = "Delete";
}


<div class="container-fluid" style="margin-top: 20px;">
    <h3 style="margin-left: 30px;">Are you sure you want to delete this author?</h3>
    <div class="row" style="margin-top: 30px;">
        <div class="col-lg-3 text-center">
            <img src="@Model.ImageUrl" style="width: 200px; height: 280px;" />
            @using (Html.BeginForm(new { page = ViewBag.Page, orderBy = ViewBag.OrderBy, search = ViewBag.Search }))
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color text-center" style="margin-top: 20px;">
                    <input type="submit" value="Delete" class="btn btn-danger" style="margin-right: 5px" />
                    <a href="@Url.Action("Index", "Authors", new { page = ViewBag.Page, orderBy = ViewBag.OrderBy, search = ViewBag.Search })" class="btn btn-default"> Back to list </a>
                </div>
            }
        </div>
        <div class="col-lg-9" style="margin-left: 50px; margin-top: -20px; margin-left: -20px;">
            <h1>@Model.Name</h1>
            <p>@Model.Description</p>
            <h3>Books:</h3>
            <ul>
                @foreach (var item in Model.Books)
                {
                    <li>@item.Name</li>
                }
            </ul>
        </div>
    </div>
</div>

E-biblioteka/Views/Authors/Details.cshtml
@model E_biblioteka.Models.Author

@{
    ViewBag.Title = "Details";
}

<div class="container" id="con">
    <div class="row">
        <h1 style="margin-left:30px;">@Model.Name</h1>
        <div class="col-lg-3" style="margin-bottom:20px; margin-top: 30px;">
            <img id="modalImage" style="width: 200px; height: 280px; margin-left: 20px;" src="@Model.ImageUrl" alt="@Model.Name" />
            <div class="text-center" style="margin-top: 20px;">
                @if (User.IsInRole("Administrator") || User.IsInRole("Employee"))
                {
                    <a href="@Url.Action("Edit", "Authors", new { id = Model.AuthorId, page = ViewBag.Page, orderBy = ViewBag.OrderBy, search = ViewBag.Search })" class="btn btn-primary" style="margin-right: 5px; margin-left: 20px;">Edit</a>
                }
                <a href="@Url.Action("Index", "Authors", new { page = ViewBag.Page, orderBy = ViewBag.OrderBy, search = ViewBag.Search })" class="btn btn-default">Back to list</a>
            </div>
        </div>
        <div class="col-lg-8 text-left" style="margin-left: 30px; margin-top: 30px;">
            @Model.Description
            @if (Model.Books.Count != 0)
            {
                <h3>
                    <b>@Html.DisplayNameFor(model => model.Books)</b>
                </h3>
                <ul>
                    @for (int i = 0; i < Model.Books.Count; i++)
                    {
                        <li>
                            @Html.ActionLink(Model.Books[i].Name, "Details", "Books", new { id = Model.Books[i].BookId, page = 1 }, new { })
                        </li>
                    }
                </ul>
            }
        </div>
    </div>
</div>

<!-- The Modal -->
<div id="myModal" class="modal">

    <!-- The Close Button -->
    <span class="close">&times;</span>

    <!-- Modal Content (The Image) -->
    <img class="modal-content" id="img01">

    <!-- Modal Caption (Image Text) -->
    <div id="caption"></div>
</div>

@section styles {
    <link rel="stylesheet" type="text/css" href="@Href("~/Content/ModalImage.css")" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <style>
        body {
            background-color: lightgray;
        }

        #con {
            background-color: white;
            border: 1px solid black;
            margin-left: auto;
            margin-right: auto;
            margin-top: 20px;
            width: 1000px;
            padding-bottom: 20px;
        }
    </style>
}

@section scripts {
    <script type="text/javascript" src="@Href("~/Scripts/ModalImage.js")"></script>
}

E-biblioteka/Views/Authors/Edit.cshtml
@model E_biblioteka.Models.Author

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm(new { page = ViewBag.Page, orderBy = ViewBag.OrderBy, search = ViewBag.Search }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Author</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.AuthorId)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImageUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImageUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    <a href="@Url.Action("Index", "Authors", new { page = ViewBag.Page, orderBy = ViewBag.OrderBy, search = ViewBag.Search } )" class="btn btn-default"> Back to list </a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

E-biblioteka/Views/Authors/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<E_biblioteka.Models.Author>

@{
    ViewBag.Title = "Index";
    var filters = "?page=" + ViewBag.Page;
    if (ViewBag.OrderBy != null)
    {
        filters += "&orderBy=" + ViewBag.OrderBy;
    }
    if (ViewBag.Search != null)
    {
        filters += "&search=" + ViewBag.Search;
    }
    if (ViewBag.BookGenre != null)
    {
        filters += "&bookGenre=" + ViewBag.BookGenre;
    }
}

<div class="container-fluid">
    <div class="row text-center">
        <h2>Authors</h2>
    </div>
    <div class="row" style="margin-bottom: 50px;">
        <span style="margin-left: 100px;">
            @if (User.IsInRole("Administrator"))
            {
                <a href="@Url.Action("Create", "Authors")" class="btn btn-primary">+ Add an author</a>
            }
        </span>
        <div class="col-xs-12 col-sm-4 col-lg-6 pull-right">
            <div class="form-inline" style="margin-left: 80px;">
                <div class="form-group">
                    <label for="search"><i class="fa fa-search"></i></label>
                    @Html.TextBox("search", "", new { @class = "form-control", @style = "width: 200px; margin-right: 15px", @placeholder = "Enter author name" })
                    <label for="order-list"><i class="fa fa-sort"></i></label>
                    <select id="order-list" class="form-control" style="width: 200px;">
                        <option value="">--Order By--</option>
                        <option value="name-ascending">Name (A-Z)</option>
                        <option value="name-descending">Name (Z-A)</option>
                    </select>
                </div>
            </div>
        </div>
    </div>
    @if (Model.Count > 0)
    {
        <div class="container-fluid text-center">
            @foreach (var item in Model)
            {
                <div class="card bg-light col-lg-4 mb-2">
                    <img class="card-img-top" src="@item.ImageUrl" style="width: 200px; height: 280px; cursor: pointer;" onclick="window.location='/Authors/Details/@item.AuthorId@filters'" />
                    <div class="card-body">
                        <h5 class="card-title">@Html.ActionLink(item.Name, "Details", "Authors", new { id = item.AuthorId, page = ViewBag.Page, orderBy = ViewBag.OrderBy, search = ViewBag.Search }, new { })</h5>
                        <p>
                            @if (User.IsInRole("Administrator") || User.IsInRole("Employee"))
                            {
                                <a href="@Url.Action("Edit", "Authors", new { id = item.AuthorId, page = ViewBag.Page, orderBy = ViewBag.OrderBy, search = ViewBag.Search })" class="btn btn-info">Edit</a>
                            }
                            @if (User.IsInRole("Administrator"))
                            {
                                <a href="@Url.Action("Delete", "Authors", new { id = item.AuthorId, page = ViewBag.Page, orderBy = ViewBag.OrderBy, search = ViewBag.Search })" class="btn btn-danger">Delete</a>
                            }
                        </p>
                    </div>
                </div>
            }
        </div>
        <div class="row">
            <div class="pagination text-center col-sm-12 col-xs-12 col-md-12 col-lg-12">
                @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page, orderBy = ViewBag.OrderBy, search = ViewBag.Search }))
            </div>
        </div>
    }
    else
    {
        <div class="row">
            <h4 class="alert alert-danger text-center">
                <span class="text-danger">No matching results!</span>
            </h4>
        </div>
    }
</div>

@section styles{
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <style>
        .card {
            margin-bottom: 25px;
        }
    </style>
}

@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {

            $("select option").each(function () {
                var value = $(this).attr("value");
                if (document.location.search.includes(value)) {
                    $(this).attr("selected", true);
                    return;
                }
            });

            var orderBy = $("#order-list").val();
            var search = $("#search").val();
            var authorsCount = @Model.Count;

            if (authorsCount == 0) {
                $("#order-list").attr("disabled", "true");
            }

            $("#search").on("change", function () {
                search = $("#search").val();
                if (orderBy)
                    document.location = "?orderBy" + orderBy + "&search=" + search;
                else
                    document.location = "?search=" + search;
            });

            $("#order-list").on("change",
                function () {
                    document.location = "?orderBy=" + this.value + "&search=" + $("#search").val();
                });

        });
    </script>
}