E-biblioteka/Models/Request.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace E_biblioteka.Models
{
    public class Request
    {
        [Display(Name = "Request ID")]
        [Key]
        public long RequestId { get; set; }
        [Required]
        [StringLength(128, ErrorMessage = "Book Title must not exceed 128 characters!")]
        public string Title { get; set; }
        [Required]
        [StringLength(64, ErrorMessage = "Author's Name must not exceed 64 characters!")]
        [Display(Name = "Author's Name")]
        public string AuthorsName { get; set; }
        public string Comment { get; set; }
    }
}

E-biblioteka/Controllers/RequestsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using E_biblioteka.Models;

namespace E_biblioteka.Controllers
{
    [Authorize]
    public class RequestsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Requests
        [Authorize(Roles = "Administrator,Employee")]
        public ActionResult Index()
        {
            return View(db.Requests.ToList());
        }

        // GET: Requests/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Request request = db.Requests.Find(id);
            if (request == null)
            {
                return HttpNotFound();
            }
            return View(request);
        }

        // GET: Requests/Create
        [Authorize(Roles = "Employee, Moderator, Member")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Requests/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Employee, Moderator, Member")]
        public ActionResult Create([Bind(Include = "RequestId,Title,AuthorsName,Comment")] Request request)
        {
            if (ModelState.IsValid)
            {
                db.Requests.Add(request);
                db.SaveChanges();
                return RedirectToAction("Index", "Books");
            }

            return View(request);
        }

        // GET: Requests/Delete/5
        [Authorize(Roles = "Administrator, Employee")]
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Request request = db.Requests.Find(id);
            if (request == null)
            {
                return HttpNotFound();
            }
            return View(request);
        }

        // POST: Requests/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, Employee")]
        public ActionResult DeleteConfirmed(long id)
        {
            Request request = db.Requests.Find(id);
            db.Requests.Remove(request);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

E-biblioteka/Views/Requests/Create.cshtml
@model E_biblioteka.Models.Request

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Request</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AuthorsName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AuthorsName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AuthorsName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "Books")
</div>

E-biblioteka/Views/Requests/Delete.cshtml
@model E_biblioteka.Models.Request

@{
    ViewBag.Title = "Delete";
}

<h2>Delete request</h2>
<div>
    <div class="container-fluid" style="margin-top: 40px; margin-bottom: 20px;">
        <h4 style="margin-left: 30px;">Are you sure you want to delete this request?</h4>
        <div class="row">
            <hr />
            <div class="col-lg-2" style="width: 10%;">
                <p style="font-weight: bold;">Book title</p>
                <p style="font-weight: bold;">Book author</p>
                <p style="font-weight: bold;">Comment</p>
            </div>
            <div class="col-lg-4" style="width: 40%;">
                <p>@Model.Title</p>
                <p>@Model.AuthorsName</p>
                <p style="width: 500px; word-wrap: break-word;">@Model.Comment</p>
            </div>
        </div>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" style="margin-right: 5px;" />
            <a href="@Url.Action("Index", "Requests")" class="btn btn-default">Back to list</a>
        </div>
    }
</div>

E-biblioteka/Views/Requests/Details.cshtml
@model E_biblioteka.Models.Request

@{
    ViewBag.Title = "Details";
}

<br>
<h2>Request details</h2>
<hr />

<div class="container" style="margin-top: 40px;">
    <div class="row">
        <div class="col-lg-2" style="width: 10%;">
            <p style="font-weight: bold;">Book title</p>
            <p style="font-weight: bold;">Book author</p>
            <p style="font-weight: bold;">Comment</p>
        </div>
        <div class="col-lg-4" style="width: 40%;">
            <p>@Model.Title</p>
            <p>@Model.AuthorsName</p>
            <p style="width: 500px; word-wrap: break-word;">@Model.Comment</p>
        </div>
    </div>
    <a href="@Url.Action("Index", "Requests")" class="btn btn-default" style="margin-top: 15px;">Back to list</a>
</div>

E-biblioteka/Views/Requests/Index.cshtml
@model IEnumerable<E_biblioteka.Models.Request>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<table id="requestsTable" class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AuthorsName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Comment)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AuthorsName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Comment)
                </td>
                <td>
                    @if (User.IsInRole("Administrator") || User.IsInRole("Employee"))
                    {
                        <a href="@Url.Action("CreateFromRequest", "Books", new { Title = item.Title, AuthorsName = item.AuthorsName, RequestId = item.RequestId }, null)" class="btn btn-success">Accept</a>
                        @:&nbsp;
                        <a href="@Url.Action("Delete", "Requests", new { id = item.RequestId })" class="btn btn-danger">Decline</a>
                        @:&nbsp;
                    }
                    <a href="@Url.Action("Details", "Requests", new { id = item.RequestId })" class="btn btn-default">Details</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@section scripts{
    <script>
        $("#requestsTable").DataTable();
    </script>
}